title: EU Funding Data
#email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
    On this page data on the distribution of recent EU funding is visualized.
#baseurl: "/jekyll" # the subpath of your site, e.g. /blog
#url: "/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
#gitlab_username:  pages

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
