---
title: "report_test"
output: html_document
date: "2022-12-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
options(scipen=999)
require("httr")
require("jsonlite")
require("RSocrata")
require("httr")
require("jsonlite")
require(ggplot2)
require(dplyr)
require(RSocrata)
require(tidyverse)
require(sf)
require(rnaturalearth)
require(rnaturalearthdata)
require(eurostat)

###### get funding data from EU commission
res <- GET("https://cohesiondata.ec.europa.eu/resource/tc55-7ysv.json?$limit=80000")
data_funding <- fromJSON(rawToChar(res$content))
data_funding$modelled_annual_eu_payments <- as.numeric(data_funding$modelled_annual_eu_payments)/1000000000
###### aggregate 
funding_average <- aggregate(modelled_annual_eu_payments~country,data_funding,sum)

period_average <- aggregate(modelled_annual_eu_payments~programming_period,data_funding,sum)

funding_average_period <- aggregate(modelled_annual_eu_payments~country+programming_period,data_funding,sum)




```

##Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}

ggplot(funding_average, aes(reorder(country,-modelled_annual_eu_payments),modelled_annual_eu_payments )) +
  coord_flip() +
  geom_bar(stat="identity", width=.90) + 
  xlab("") + # Set axis labels
  ylab("") + 
  ggtitle("total funding by country since 1989 in billion euro") + 
  theme_minimal()

ggplot(period_average, aes(reorder(programming_period,-modelled_annual_eu_payments),modelled_annual_eu_payments )) +
  coord_flip() +
  geom_bar(stat="identity", width=.90) + 
  xlab("") + # Set axis labels
  ylab("") + 
  ggtitle("total funding by programming period in billion euro") + 
  theme_minimal()

ggplot(funding_average_period[funding_average_period$programming_period=="1989-1993",], aes(reorder(country,-modelled_annual_eu_payments),modelled_annual_eu_payments )) +
  coord_flip() +
  geom_bar(stat="identity", width=.90) + 
  xlab("") + # Set axis labels
  ylab("") + 
  ggtitle("total funding by country 1989-1993 in billion euro") + 
  theme_minimal()


ggplot(funding_average_period[funding_average_period$programming_period=="2014-2020",], aes(reorder(country,-modelled_annual_eu_payments),modelled_annual_eu_payments )) +
  coord_flip() +
  geom_bar(stat="identity", width=.90) + 
  xlab("") + # Set axis labels
  ylab("") + 
  ggtitle("total funding by country since 2014-2020 in billion euro") + 
  theme_minimal()



# Disposable income of private households by NUTS 2 regions at 1:60mln res
library(eurostat)
library(dplyr)
library(ggplot2)
library(geometry)
#data_eurostat <- get_eurostat("demo_pjan") %>%
#  dplyr::filter(cat == "TOTAL")%>%
  # classifying the values the variable
#> Reading cache file /tmp/RtmpnlYDei/r_cache2/tgs00026_raw_code_FF.rds
#> Table  tgs00026  read from cache file:  /tmp/RtmpnlYDei/r_cache2/tgs00026_raw_code_FF.rds

# Download geospatial data from GISCO
data_geo <- get_eurostat_geospatial(resolution = "60", nuts_level = "0", year = 2021)
#> Object cached at /tmp/RtmpnlYDei/r_cache2/sf60220214326.RData
#> sf at resolution 1: 60  cached at:  /tmp/RtmpnlYDei/r_cache2/sf60220214326.RData
#> Warning in get_eurostat_geospatial(resolution = "60", nuts_level = "2", :
#> Default of 'make_valid' for 'output_class="sf"' will be changed in the future
#> (see function details).

# merge with attribute data with geodata
data <- merge(data_geo,funding_average, by.x="NUTS_ID",by.y="country")
data$cat <- cut_to_classes(data$modelled_annual_eu_payments)

## Joining, by = "geo"
ggplot(data = data) +
  geom_sf(aes(fill = cat), size = 0.1) +
  scale_fill_brewer(palette = "Oranges") +
  guides(fill = guide_legend(reverse = TRUE, title = "billion euro")) +
  labs(
    title = "Total fiscal transfers",
    caption = ""
  ) +
  theme_light() +
  theme(legend.position = c(.8, .8)) +
  coord_sf(xlim = c(-12, 44), ylim = c(35, 70))



ggplot(data) + 
  geom_sf() +
  coord_sf()











```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
