name: Test Python and R environment

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
#Modifies default permission granted to GITHUB_TOKEN (Not fully sure if and what needed though)  
#permissions:
 # contents: read/write
 # issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: rocker/verse
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Every time
        run: echo "This step will always run" 
      # Load repo
      - uses: actions/checkout@v3
      - run: git version
      - run: |
          git config --global --add safe.directory /__w/eu-funding/eu-funding
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git pull
          
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
          
      - run: rm -rf README.md
      # Set-up R
      - name: Install packages
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("eurostat")'
          Rscript -e 'install.packages("httr")'
          Rscript -e 'install.packages("jsonlite")'
          Rscript -e 'install.packages("RSocrata")'
          Rscript -e 'install.packages("ggplot2")'
          Rscript -e 'install.packages("dplyr")'
          Rscript -e 'install.packages("sf")'
          Rscript -e 'install.packages("rnaturalearth")'
          Rscript -e 'install.packages("rnaturalearthdata")'
          Rscript -e 'install.packages("geometry")'
      # Run R script 
      - run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      # List all files in directory (l-longform  a-all h-human readable)     
      - name: List all file  
        run: ls -lah  
      # Commit files
      - name: Commit files
        run: |
          git add README.md README_files/figure-markdown_strict
          git commit -m "Update README.md via GH Actions"
          git push
